image: Visual Studio 2022

environment:
  PROJECT: 'src/Solution/Solution.sln'

configuration:
  - Debug

before_build:
  - nuget restore src/Solution/Solution.sln

build:
  project: src/Solution/Solution.sln
  publish_wap: true
  verbosity: minimal
