image: Visual Studio 2022

environment:
  project: src/Solution/Solution.sln

configuration:
  - Debug

before_build:
  - nuget restore {project}

build:
  project: {project}
  verbosity: minimal
  
after_build:
  cmd: echo 'after build!'
