version: 1.1.{build}

branches:
  only:
    - main
    - develop
  except:
    - /feature/
    
init:
  - echo Hello init!
  - cmd: set FIRST_VAR=INSTALL
  - echo %FIRST_VAR%

image: Visual Studio 2022

matrix:
  fast_finish: true

install:
  - echo Hello from INIT
  - echo set FIRST_VAR=INIT
  - echo %FIRST_VAR%
  
platform: Any CPU
  
configuration:
  - Debug
  - Release
  
before_build:
  - echo set FIRST_VAR=BEFORE_BUILD
  - echo %FIRST_VAR%
  - nuget restore src/Solution/Solution.sln
  

build:
  project: src/Solution/Solution.sln
  publish_azure: true
  verbosity: minimal
  
artifacts:
  - path: src/Solution/Web/bin/$(configuration)
    name: web-app
  
on_success:
  - echo SUCCESS!
  
on_failure:
  - echo FAILURE!
  
on_finish:
  - echo FINISH!
