image: Visual Studio 2019

install:
  - dotnet tool install -g codecov.tool

configuration:
  - Release


build_script:
  - cmd:  dotnet build src/Solution/Solution.sln /p:CollectCoverage=true /p:CoverletOutputFormat=OpenCover /p:CoverletOutput=./Coverage.xml
  
after_build:
  - codecov -f ./Coverage.*.xml
